apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhttp-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jhttp-web
  template:
    metadata:
      labels:
        app: jhttp-web
    spec:
      containers:
      - name: jhttp-container
        # This tells Kubernetes to look in values.yaml for the 'image' key
        image: {{ .Values.image }} 
        ports:
        - containerPort: 8888
