apiVersion: v1
kind: Service
metadata:
  name: jhttp-service
spec:
  type: LoadBalancer             # This gives you an external IP address
  selector:
    app: jhttp-web               # This MUST match the label in the Deployment above
  ports:
    - protocol: TCP
      port: 80                   # The port you type in your browser
      targetPort: 8888           # The port the app is actually listening on
